cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'hashicorp/tap'

brew 'ansible'
brew 'coreutils'
brew 'grc'
brew 'hashicorp/tap/terraform'
brew 'starship'

brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'

cask 'vscodium'
cask 'orbstack'
cask 'knockknock'