cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'hashicorp/tap'

brew 'ansible'
brew 'coreutils'
brew 'grc'
brew 'hashicorp/tap/terraform'
brew 'starship'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'knockknock'
cask 'mos'
cask 'orbstack'
cask 'vscodium'