#!/bin/bash

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

setup_gitconfig () {
  if ! [ -f shared/git/gitconfig.local.symlink ]
  then
    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    echo 'What is your github author name?'
    read -e git_authorname
    echo 'What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" shared/git/gitconfig.local.symlink.example > shared/git/gitconfig.local.symlink
  fi
}

link_file () {
  local src=$1 dst=$2

  if [[ -f "$dst" || -d "$dst" || -L "$dst" ]]
  then
    rm -rf "$dst"
  fi
    ln -s "$1" "$2"
}

install_dotfiles () {
  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H $1 -maxdepth 2 -name '*.symlink')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_dotfiles $DOTFILES_ROOT/shared

find $DOTFILES_ROOT/shared -name install.sh | while read installer ; do sh -c "${installer}" ; done

if [[ "$(uname)" == "Darwin" ]]; then
  echo 'macos'
  install_dotfiles $DOTFILES_ROOT/macos
  find $DOTFILES_ROOT/macos -name install.sh | while read installer ; do sh -c "${installer}" ; done
elif [[ "$(uname)" == "Linux" ]]; then
  echo 'linux' 
  install_dotfiles $DOTFILES_ROOT/linux
  find $DOTFILES_ROOT/linux -name install.sh | while read installer ; do sh -c "${installer}" ; done
else
  echo 'unknown system'
fi