#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if test $(which brew)
then
  echo "› brew bundle"
  brew bundle
fi
if test $(which apt)
then
  echo "› apt bundle"
  apt-bundle $ZSH/Debfile
fi


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done